
SET(TOOLSCHAIN_PATH "/")
SET(TOOLCHAIN_HOST "${TOOLSCHAIN_PATH}usr/bin/")

SET(TOOLCHAIN_CC "${TOOLCHAIN_HOST}gcc")
SET(TOOLCHAIN_CXX "${TOOLCHAIN_HOST}g++")

SET(CMAKE_CROSSCOMPILING TRUE)

# Define name of the target system
SET(CMAKE_SYSTEM_NAME "Linux")
# Define the compiler
SET(CMAKE_C_COMPILER ${TOOLCHAIN_CC})
SET(CMAKE_CXX_COMPILER ${TOOLCHAIN_CXX})

SET(CMAKE_FIND_ROOT_PATH "${CMAKE_PREFIX_PATH}" "${TOOLSCHAIN_PATH}")

# search for programs in the build host directories
SET(CMAKE_FIND_ROOT_PATH_MODE_PROGRAM NEVER)
# for libraries and headers in the target directories
SET(CMAKE_FIND_ROOT_PATH_MODE_LIBRARY ONLY)
SET(CMAKE_FIND_ROOT_PATH_MODE_INCLUDE ONLY)
SET(CMAKE_FIND_ROOT_PATH_MODE_PACKAGE ONLY)